server:
        addr: 127.0.0.1:9999
        activation: false    # activation strategy
        expire: 604800       # 60 * 60 * 24 * 7
jwt:
        secret-key: MySecretKey
mysql:
        username: root
        password: 
        host: localhost
        port: 3306
        dbname: test1
redis:
        addr: localhost:6379
email:
        host: smtp.163.com
        port: 485
        address: pangold@163.com
        password: "******"
sms:
        url: https://aaaaaaaaaa.com
        token: xxxx
